src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $topic;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="posts",fetch="EAGER")
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_post;

    /**
     * @ORM\OneToMany(targetEntity=Reponse::class, mappedBy="post",fetch="EAGER",cascade={"persist","remove"})
     */
    private $reponses;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTopic(): ?string
    {
        return $this->topic;
    }

    public function setTopic(string $topic): self
    {
        $this->topic = $topic;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDatePost(): ?\DateTimeInterface
    {
        return $this->date_post;
    }

    public function setDatePost(\DateTimeInterface $date_post): self
    {
        $this->date_post = $date_post;

        return $this;
    }

    /**
     * @return Collection|Reponse[]
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses[] = $reponse;
            $reponse->setPost($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): self
    {
        if ($this->reponses->contains($reponse)) {
            $this->reponses->removeElement($reponse);
            // set the owning side to null (unless already changed)
            if ($reponse->getPost() === $this) {
                $reponse->setPost(null);
            }
        }

        return $this;
    }
}

src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReponseRepository::class)
 */
class Reponse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reponse;

    /**
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="reponses",fetch="EAGER")
     */
    private $post;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_reponse;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="reponses",fetch="EAGER")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(string $reponse): self
    {
        $this->reponse = $reponse;

        return $this;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): self
    {
        $this->post = $post;

        return $this;
    }

    public function getDateReponse(): ?\DateTimeInterface
    {
        return $this->date_reponse;
    }

    public function setDateReponse(\DateTimeInterface $date_reponse): self
    {
        $this->date_reponse = $date_reponse;

        return $this;
    }

    public function getUser(): ?Utilisateur
    {
        return $this->user;
    }

    public function setUser(?Utilisateur $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/Support.php
<?php

namespace App\Entity;

use App\Repository\SupportRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SupportRepository::class)
 */
class Support
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Matiere::class, inversedBy="supports",fetch="EAGER")
     */
    private $matiere;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\OneToMany(targetEntity=Deposer::class, mappedBy="support",fetch="EAGER",cascade={"persist","remove"})
     */
    private $deposers;

    /**
     * @ORM\Column(type="string", length=4)
     */
    private $espace_depot;

    public function __construct()
    {
        $this->deposers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getMatiere(): ?Matiere
    {
        return $this->matiere;
    }

    public function setMatiere(?Matiere $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    /**
     * @return Collection|Deposer[]
     */
    public function getDeposers(): Collection
    {
        return $this->deposers;
    }

    public function addDeposer(Deposer $deposer): self
    {
        if (!$this->deposers->contains($deposer)) {
            $this->deposers[] = $deposer;
            $deposer->setSupport($this);
        }

        return $this;
    }

    public function removeDeposer(Deposer $deposer): self
    {
        if ($this->deposers->contains($deposer)) {
            $this->deposers->removeElement($deposer);
            // set the owning side to null (unless already changed)
            if ($deposer->getSupport() === $this) {
                $deposer->setSupport(null);
            }
        }

        return $this;
    }

    public function getEspaceDepot(): ?string
    {
        return $this->espace_depot;
    }

    public function setEspaceDepot(string $espace_depot): self
    {
        $this->espace_depot = $espace_depot;

        return $this;
    }
}

templates/about.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% endblock %}
{% block bodtt %}

<style>
	.img {
		border:2px solid #fff;
		box-shadow: 2px 2px 2px 2px white;
		-moz-box-shadow: 2px 2px 2px white;
		-webkit-box-shadow: 2px 2px 2px white;
		-khtml-box-shadow: 2px 2px 2px white;
	}
	a{
		color:#1b6d85;
	}

</style>

	<header>
		<div style="background-color:#D0FAFB ;width: 100%;height:1000px;position: relative">
			<img src="{{asset('images/about.png')}}" width="50%" height="600px" alt="about UNISET" style="margin-left:25%;margin-top:200px;opacity: 0.8" class="shadow-lg p-3 mb-5 rounded"/>
		</div>


		

	</header>
	<h1 style="text-align:center; font-weight:bold; margin-top:50px">Contactez Nous</h1>
	{% form_theme form 'bootstrap_4_layout.html.twig' %}

	<div id="fh5co-contact">
		<div class="container">
			<div class="row">
				<div class="col-md-5 col-md-push-1 animate-box">
					
					<div class="fh5co-contact-info">
						<h3>Contact Information</h3>
						<ul>
							<li class="address">47, Rue des Entrepreneurs Charguia II <br>2035- Tunis Carthage (Tunisie)</li>
							<li class="phone"><a href="tel://1234567920">+216 11111111</a></li>
							<li class="email"><a href="mailto:karkaradsi21@gmail.com">karkaradsi21@gmail.com</a></li>
						</ul>
					</div>

				</div>

				<div class="col-md-6 animate-box">
					<h3>Get In Touch</h3>
					{{ form_start(form) }}

						<div class="row form-group">
							<div class="col-md-6" >
								<!-- <label for="fname">First Name</label> -->
								{{ form_widget(form.prenom) }}
							</div>
							<div class="col-md-6" >
								<!-- <label for="lname">Last Name</label> -->
								{{ form_widget(form.nom) }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<!-- <label for="email">Email</label> -->
								{{ form_widget(form.email) }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12">
								<!-- <label for="subject">Subject</label> -->
								{{ form_widget(form.sujet) }}
							</div>
						</div>

						<div class="row form-group">
							<div class="col-md-12" >
								<!-- <label for="message">Message</label> -->

							{{ form_widget(form.contenu) }}
							</div>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary ">Send Message</button>
						</div>

					{{ form_end(form) }}
				</div>
			</div>

		</div>
	</div>



	<!------------------------------------------------------------>




<!-- jQuery -->
{% endblock %}

templates/ajout_support.html.twig
{% block title %}Enseignant {% endblock %}
{% include 'header.html.twig' %}
{% block body %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <style>
        #search{
            border:none;
            padding:15px;
            width: 530px;
        }
    </style>
    <body style="background-color:#D5E9F1 ">
    <div class="main" >
        <div style="margin-left:900px;margin-top: 20px;width: 150px;height: 30px;">
            <i class="fas fa-envelope" style="font-size:20px" title="Messages"></i>
            <span class="badge badge-notify" >2</span>
            &nbsp; &nbsp; &nbsp;<i class="fa fa-sign-out" style="font-size:20px" title="Logout"></i>
        </div>
        <h2 style="margin-left:120px;margin-top: -40px ">Supports</h2>
        <img src="/images/adminis/{{ app.user.img}}" style="margin-left:120px;border-radius: 50%; " alt="userImg" width="45px" height="45px">
        <h4 style="margin-left:180px;margin-top: -34px "> {{app.user.username}} </h4>
        <input style="position:absolute;margin-top: 30px;margin-left: 150px" id="search" placeholder="search..."/> <button style="border:none;margin-left:680px;width:70px;margin-top:30px;padding:18px;" class="btn-info"><i class="fa fa-search" aria-hidden="true"></i></button>
        <div style="background-color:white;border-radius:0%;width:600px;height: 750px;position:absolute;margin-left:150px;margin-top:20px">
          <h4  style="margin-left:15px;color:#1b6d85;margin-top: 14px">Mes supports ajoutés </h4>
            <hr>
            <table class="table table-hover text-center">
                <thead class="thead-dark">
                <tr style="text-align: center;color:#5cb85c;font-family: Calibri,serif">
                    <th scope="col"  style="font-size: 15px">Libellé</th>
                    <th scope="col" style="font-size: 15px">Type</th>
                    <th scope="col"  style="font-size: 15px">Matière</th>
                    <th scope="col" style="font-size: 15px" colspan="2">Date d'ajout</th>
                </tr>
                </thead>
                <tbody>
                {% for matiere in matieres %}
                {%  for supp in matiere.matiere.supports %}
                    <tr style="font-size: 13px;text-align: center">
                        <td style="font-weight: bold">{{ supp.nom }}</td>
                        <td style="font-weight: bold">{{ supp.type }}</td>
                        <td style="font-weight: bold">{{ supp.matiere.libelle }}</td>
                        <td style=";font-size: 12px">{{ supp.dateAjout |date("m/d/Y") }}</td>
                        <td><a href="{{ asset('uploads/supports/' ~ supp.contenu) }}"><button class="btn btn-select-plan"> View file</button></a></td>
                        <td style="color:#8c8c8c;font-size: 12px"><a href="{{path('deletesupport',{'id': supp.id}) }}"><button class="btn" style="padding: 10px"  ><i class="fas fa-trash-alt"></i></button></a></td>
                    </tr>
                {% endfor %}
                {% endfor %}
                </tbody>
            </table>
            <a href="{{ path('enst')}}" ><button style="margin-left:220px;padding: 13px;width: 120px;border:none;" class="btn-info">Retour</button></a>
        </div>
        <div style="background-color:white;border-radius:0%;width:350px;height: 750px;position:absolute;margin-left:770px;margin-top:-55px">
            <br><br>
            <h4 style="color:orangered;text-align: center;margin-top: -8px">Ajouter un Support</h4>
            <hr>
            {{ form_start(form,{'action': path('ajout_support')}) }}
            <select name="matiere" id="mat" style="padding: 12px;margin-left:37px;width: 275px">
                <option selected disabled>Matière</option>
                {% for matiere in matieres %}
                <option value ="{{ matiere.matiere.id}}" id="a">{{ matiere.matiere.libelle}}</option>
                {% endfor %}
            </select>
            {{ form_widget(form.nom) }}
            {{ form_widget(form.contenu) }}
            {{ form_widget(form.type) }}
            {{ form_widget(form.espaceDepot) }}
            <br><br>
            <button class="btn-info" style="border: none;padding: 13px;margin-left: 31%;width:120px;" type="submit" >Ajouter</button>
            {{ form_end(form) }}
        <div id="piechart"></div>
        <script type="text/javascript">
            // Load google charts
            google.charts.load('current', {'packages':['corechart']});
            google.charts.setOnLoadCallback(drawChart);
            //window.alert(tab);
            // Draw the chart and set the chart values
            function drawChart() {
                var data = google.visualization.arrayToDataTable(
                    [
                        ['ISET', 'SupportsLibrairieParIsets'],
                        {% for matiere in matieres %}
                        ["{{ matiere.matiere.libelle }}", {{matiere.matiere.supports |length}} ],
                        {% endfor %}
                    ]);
                // Optional; add a title and set the width and height of the chart
                var options = {'title':" Nombres de supports par matière", 'width':350, 'height':400};
                // Display the chart inside the <div> element with id="piechart"
                var chart = new google.visualization.PieChart(document.getElementById('piechart'));
                chart.draw(data, options);
            }
        </script>
    </div>
    </div>
    </body>
    {% include 'footer.html.twig' %}
{% endblock %}

templates/base.html.twig
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>uniset</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Free HTML5 Website Template by freehtml5.co" />
    <meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="freehtml5.co" />

    <!--
    //////////////////////////////////////////////////////

    FREE HTML5 TEMPLATE
    DESIGNED & DEVELOPED by FreeHTML5.co

    Website: 		http://freehtml5.co/
    Email: 			info@freehtml5.co
    Twitter: 		http://twitter.com/fh5co
    Facebook: 		https://www.facebook.com/fh5co

    //////////////////////////////////////////////////////
     -->

    <!-- Facebook and Twitter integration -->
    <meta property="og:title" content=""/>
    <meta property="og:image" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:site_name" content=""/>
    <meta property="og:description" content=""/>
    <meta name="twitter:title" content="" />
    <meta name="twitter:image" content="" />
    <meta name="twitter:url" content="" />
    <meta name="twitter:card" content="" />
    <link rel="icon" href="{{ asset('images/lasticon.ico') }}" />
    <script src="https://kit.fontawesome.com/a9aa160619.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="{{ asset('css/animate.css')}}">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="{{ asset('css/icomoon.css')}}">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css')}}">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="{{ asset('css/magnific-popup.css')}}">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="{{ asset('css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{ asset('css/owl.theme.default.min.css')}}">

    <!-- Theme style  -->
    <link rel="stylesheet" href="{{ asset('css/style.css')}}">

    <!-- Modernizr JS -->
    <script src="{{ asset('js/modernizr-2.6.2.min.js')}}"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]-->
    <script src="{{ asset('js/respond.min.js')}}"></script>
    <![endif]-->
    <style>

    </style>

</head>
<body>

<div class="fh5co-loader"></div>

<div id="page">
    <nav class="fh5co-nav" role="navigation">
        
        <div class="top-menu" >
            <div class="container">
                <div class="row">
                    <div class="col-xs-1">
                        <svg class="Icon_material_school" viewBox="1.5 4.5 172.964 170.508" style="color: rgba(255,106,76,1);">
                            <path fill="rgba(55,66,145,1)" id="Icon_material_school" d="M 32.94804382324219 100.9316787719727 L 32.94804382324219 138.8223266601563 L 87.98211669921875 175.0078735351563 L 143.0161743164063 138.8223266601563 L 143.0161743164063 100.9316787719727 L 87.98211669921875 137.1172332763672 L 32.94804382324219 100.9316787719727 Z M 87.98211669921875 4.499999046325684 L 1.499999761581421 61.33596038818359 L 87.98211669921875 118.1719207763672 L 158.7402038574219 71.66116333007813 L 158.7402038574219 137.1172332763672 L 174.4642181396484 137.1172332763672 L 174.4642181396484 61.33596038818359 L 87.98211669921875 4.499999046325684 Z">
                            </path>
                        </svg>
                        <div id="UNISET" >
                            <span style="color:white;">&nbsp;&nbsp;UNISET</span>
                        </div>
                    </div>
                    <div class="col-xs-11 text-right menu-1">
                        <ul>
                            <li class="active"><a href="{{path('login')}}">Accueil</a></li>
                            <li><a href="{{path('login')}}">Cours</a></li>
                            <li><a href="{{path('about-UNISET')}}">Contact</a></li>
                            <li class="btn-cta"><a href="{{path('login')}}"><span>S'identifier</span></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </nav>

    {% block bodtt  %}{% endblock %}
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
</div>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>


<!-- jQuery -->

<script src="{{ asset('js/jquery.min.js')}}"></script>
<!-- jQuery Easing -->
<script src="{{ asset('js/jquery.easing.1.3.js')}}"></script>
<!-- Bootstrap -->
<script src="{{ asset('js/bootstrap.min.js')}}"></script>
<!-- Waypoints -->
<script src="{{ asset('js/jquery.waypoints.min.js')}}"></script>
<!-- Stellar Parallax -->
<script src="{{ asset('js/jquery.stellar.min.js')}}"></script>
<!-- Carousel -->
<script src="{{ asset('js/owl.carousel.min.js')}}"></script>
<!-- countTo -->
<script src="{{ asset('js/jquery.countTo.js')}}"></script>
<!-- Magnific Popup -->
<script src="{{ asset('js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{ asset('js/magnific-popup-options.js')}}"></script>
<!-- Main -->
<script src="{{ asset('js/main.js')}}"></script>

</body>
</html>

templates/footer.html.twig
<!-- Main -->
<script src="{{ asset('js/main.js') }}"></script>
<footer>
    <div class="container" style="width: 72%;height: 190px;background-color:#F5F7FA ;margin-top: 650px;position:relative;margin-left: 320px">

            <img src="{{ asset('images/uniset.png') }}" width="100px" height="100px" style="margin-left: 45%;margin-top: 30px" alt="img">
        <h5 style="color: #122b40;font-weight: bold;text-align: center;"> All rigths reserved  <i class="far fa-copyright"></i>  2020 <br>
      Developed by KARKARATEAM</h5>


    </div>
</footer>

templates/post.html.twig
{% include 'header.html.twig' %}
{% block body %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        hr{
            color:darkorange;
            height: 8px;
        }
        tr th{
            font-weight: bold;
        }
        /* Chat containers */
        .container {
            border: 2px solid #dedede;
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 5px;
            margin: 10px 0;
            margin-left: 140px ;
            width:85%;
            height: 150px;
        }
        .container1 {
            border: 2px solid #dedede;
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 5px;
            margin: 10px 0;
            margin-left: 170px ;
            width:75%;
            height: 120px;
        }
        /* Darker chat container */
        .darker {
            border-color: #ccc;
            background-color: #ddd;
        }
        /* Clear floats */
        .container::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Style images */
        .container img {
            float: left;
            max-width: 40px;
            width: 100%;
            margin-right: 20px;
            border-radius: 50%;
        }
        .container1::after {
            content: "";
            clear: both;
            display: table;
        }

        /* Style images */
        .container1 img {
            float: left;
            max-width: 40px;
            width: 100%;
            margin-right: 20px;
            border-radius: 50%;
        }

        /* Style the right image */
        .container img.right {
            float: right;
            margin-left: 20px;
            margin-right:0;
        }

        /* Style time text */
        .time-right {
            float: right;
            color: #aaa;
        }

        /* Style time text */
        .time-left {
            float: left;
            color: #999;
        }
        .container2 {
            border-radius: 5px;
            background-color: transparent;
            padding: 20px;
            width: 700px;
            margin-left: 250px;
        }
    </style>
    <body style="background-color: #D5E9F1 ">
    <div class="main" >
        <h3 style="margin-left:120px ">Espace Etudiant <span style="color:#1b6d85"> <i class="fas fa-angle-double-right" style="font-size: 18px"></i>  Forum de discussion  <i class="fas fa-angle-double-right" style="font-size: 18px"></i> {{ post.topic }} </span></h3>
        <br>
        <br>
            <div class="container">
                <img src="/images/adminis/{{post.user.img}}"  alt="Avatar">
                <span style="font-size: 15px;color: #aaa;">{{ post.user.username}}</span>
                <br>
                <h4>{{ post.topic}}</h4>
                <h5>{{ post.contenu}}</h5>
                <span class="time-right">
                    <i class="far fa-comment"></i> {{ post.reponses |length}} réponses | {{ post.datePost | date}}
                    {% if app.user.username ==post.user.username%}
                        <br><a href="{{ path('delpost',{'id':post.id}) }}"> <i class="fas fa-trash" title="Supprimer ce post" style="margin-left: 200px;font-size: 22px;margin-top: 8px"></i></a>
                    {% endif %}
                </span>
            </div>
        {% for reponse in reponses %}
        <div class="container1">

            <img src="/images/adminis/{{reponse.user.img}}"  alt="Avatar">
            <span style="font-size: 15px;color: #aaa;">{{ reponse.user.username}}</span>
            <br>
            <h5>{{ reponse.reponse}}</h5>
            <span class="time-right">
                {{reponse.dateReponse | date}}
                {% if app.user.username ==reponse.user.username%}
                    <br><a href="{{ path('delreponse',{'id':reponse.id}) }}"><i class="fas fa-trash" style="margin-left: 110px;font-size: 22px;margin-top: 5px" title="Supprimer cette réponse"></i></a>
                {% endif %}
            </span>
        </div>

        {% endfor %}
        <div class="container2">
            {{ form_start(form ,{'action':path('addreponse',{'id':post.id})}) }}
            {{ form_widget(form.reponse)}}
            <button type="submit" class="btn btn-success" style="margin-left: 20px;width:100px;padding:21px;margin-top: -60px">Envoyer</button>
            {{ form_end(form) }}
        </div>

    </div>
    </body>
{% endblock %}